### ISSUE TITLE
FYI https://libgit2.org/ might be useful

### ISSUE THREAD

**Issue by markfirmware** [zigtools/zpm#1]
https://libgit2.org/

**Comment by ikskuh** [comment]
I don't think adding another dependency is a good idea. You need `git` installed anyways, so using that executable seems reasonable to me.

**Comment by markfirmware** [comment]
Makes sense.

**Comment by Not-Nik** [comment]
Just saw this: using `libgit` instead of the `git` command could make stuff a lot easier, considering the library can be linked statically while the command has to be present on the system independently from the main executable.

**Comment by ikskuh** [comment]
This is something to consider actually. Would make one dependency from runtime to compile time… But will also increase the project complexity itself a lot, probably doubling code size…

let me think about it
