### ISSUE TITLE
maybe detect package api versions automatically e.g. elm

### ISSUE THREAD

**Issue by markfirmware** [zigtools/zpm#2]
Enforced Semantic Versioning

Elm can detect all API changes automatically thanks to its type system. We use that information to guarantee that every single Elm package follows semantic versioning precisely. No surprises in PATCH releases.

https://elm-lang.org

**Comment by ikskuh** [comment]
Package versioning is out of scope for `zpm`. It does not try to be a full-featured versioning tool or similar, but help people set up their projects quickly.

Having stable packaging for an unstable programming language seems kind of unnecessary for me.
