### ISSUE TITLE
only GitHub?

### ISSUE THREAD

**Issue by akavel** [zigtools/zpm#4]
There are other Git hosting possibilities than GitHub and some people may have reasons to not want or not be able to use GitHub. Other websites include GitLab, sr.ht, as well as private hosting (incl. e.g. on a Raspberry Pi). Now, it looks like zpm is only limited to GitHub? If yes, it would be good if it was extended to also support other hosting servers, for example by allowing full HTTP/HTTPS URL for fetching a repository from non-GitHub.

**Comment by ikskuh** [comment]
This is a non-issue as `zpm install <arg>` is only doing `git submodule add https://github.com/$MAGIC/<arg>` where `$MAGIC` is determined by calling the GitHub API once.

If you don't want to use GitHub, just use `git submodule` directly ;)

ZPM does not and will never have it's own registry
